### ISSUE TITLE
Causes IMDb app to crash

### ISSUE THREAD

**Issue by NHellFire** [chiehmin/MinMinGuard#115]
Currently running 2.0 alpha 15.
Log:
```
05-30 02:05:51.125 E/AndroidRuntime(12777): FATAL EXCEPTION: main
05-30 02:05:51.125 E/AndroidRuntime(12777): Process: com.imdb.mobile, PID: 12777
05-30 02:05:51.125 E/AndroidRuntime(12777): java.lang.IllegalArgumentException: result has type boolean, got java.lang.Object
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at com.amazon.device.ads.AdLayout.loadAd(<Xposed>)
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at com.imdb.mobile.mvp.presenter.ads.AmazonAdLoader$1.run(AmazonAdLoader.java:75)
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at android.os.Handler.handleCallback(Handler.java:739)
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at android.os.Looper.loop(Looper.java:158)
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at android.app.ActivityThread.main(ActivityThread.java:7224)
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at java.lang.reflect.Method.invoke(Native Method)
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-30 02:05:51.125 E/AndroidRuntime(12777): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
```

**Comment by chiehmin** [comment]
Great log. The bug should be fixed with 791006c8065794302078846889872650689879d8

**Comment by Casonctin** [comment]
It stopped crashing IMDB, but IMDB images take forever to load.
