### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by aleung** [chiehmin/MinMinGuard#14]
java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.ViewGroup
	at tw.fatminmin.xposed.minminguard.Main.removeAdView(Main.java:297)
	at tw.fatminmin.xposed.minminguard.Main.removeAdView(Main.java:318)
	at tw.fatminmin.xposed.minminguard.Main.removeAdView(Main.java:318)
	at tw.fatminmin.xposed.minminguard.Main.removeAdView(Main.java:318)
	at tw.fatminmin.xposed.minminguard.Main.removeAdView(Main.java:318)
	at tw.fatminmin.xposed.minminguard.Main.removeAdView(Main.java:318)
	at tw.fatminmin.xposed.minminguard.Main.removeAdView(Main.java:318)
	at tw.fatminmin.xposed.minminguard.Main.removeAdView(Main.java:318)
	at tw.fatminmin.xposed.minminguard.Main.removeAdView(Main.java:318)
	at tw.fatminmin.xposed.minminguard.Main$3.afterHookedMethod(Main.java:171)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.view.ViewGroup.addView(Native Method)
	at com.morrison.applocklite.n.run(Unknown Source)
	at android.app.Activity.runOnUiThread(Activity.java:4713)
	at com.morrison.applocklite.BaseActivity.a(Unknown Source)
	at com.morrison.applocklite.BaseActivity.e(Unknown Source)
	at com.mobfox.sdk.n.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5144)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by chiehmin** [comment]
Can you provide more information? (ie. which app?)

**Comment by aleung** [comment]
Sorry, it was too long ago. Will provide more information next time.

**Comment by pylerSM** [comment]
Sept 2014. Maybe it was already fixed.

Edit: Code from sept 2014: https://github.com/chiehmin/MinMinGuard/blob/5ba9130f28e5ca1afa17b762bb0f8173dc6f072f/src/tw/fatminmin/xposed/minminguard/Main.java#L297

Now, we have no such code.
