### ISSUE TITLE
程序fc

### ISSUE THREAD

**Issue by lukemin** [chiehmin/MinMinGuard#164]
java.lang.IllegalArgumentException: Component class tw.fatminmin.xposed.minminguard.ui.MainActivity-Alias does not exist in tw.fatminmin.xposed.minminguard
	at android.os.Parcel.readException(Parcel.java:1688)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:4369)
	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:2084)
	at tw.fatminmin.xposed.minminguard.ui.dialog.SettingsDialogFragment$1.onClick(SettingsDialogFragment.java:58)
	at com.shang.xposed.XposedBigBang$ViewOnClickListenerHooker$1.onClick(XposedBigBang.java:608)
	at android.view.View.performClick(View.java:5656)
	at android.view.View$PerformClick.run(View.java:22501)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by chiehmin** [comment]
Fixed in 78388d2c2ecde753dc99583741eac7f1f27e08d6

**Comment by lukemin** [comment]
thanks for your great job

**Comment by lukemin** [comment]
thanks for your great job
